### ISSUE TITLE
error when pwd gets updated in ENC

### ISSUE THREAD

**Issue by schewara** [puppetlabs/puppetlabs-java_ks#11]
Just tried out the module, with the password coming from an ENC (Foreman)

when changing the password in he ENC, puppet does not regenerate the keystore, but tries to update it with the new password which naturally fails and leaves the system in an inconsistent state

debug: Executing 'keytool -importcert -noprompt -alias puppetca -file /var/lib/puppet/ssl/certs/ca.pem -keystore /etc/pki/testvm02.localdomain.ks -trustcacerts'
err: /Stage[main]/Java_ks::Host/Java_ks[puppetca:keystore]/ensure: change from absent to latest failed: Execution of 'keytool -importcert -noprompt -alias puppetca -file /var/lib/puppet/ssl/certs/ca.pem -keystore /etc/pki/testvm02.localdomain.ks -trustcacerts' returned 1: Enter keystore password:  keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
