### ISSUE TITLE
undefined method 'environment' when $environment used in puppet:// URI

### ISSUE THREAD

**Issue by schewara** [puppetlabs/puppetlabs-java_ks#31]
Just updated to the latest version and get following error when trying to use
an environment specific path in the puppet URI

(/Stage[main]/Jumio::Role::Platform/Java_ks::Keystore[platform]/Java_ks[myks:keystore]/ensure) change from absent to latest failed: Could not set 'latest on ensure: undefined method `environment' for #Puppet::Resource::Catalog:0x7f2ca4f0fa78 at /etc/puppet/environments/test/modules/java_ks/manifests/keystore.pp:51

the implementation is the following

  java_ks { "${title}:keystore":
    ensure       => $ensure,
    certificate  => "puppet:///ssl/${environment}/${certificate}",
    private_key  => "puppet:///ssl/${environment}/${private_key}",
    target       => "${path}/${title}.jks",
    password     => $password,
    trustcacerts => $trustcacerts,
  }

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
