### ISSUE TITLE
certificate or certificate_content parameter is required when removing entries from Keystores

### ISSUE THREAD

**Issue by simioa** [puppetlabs/puppetlabs-java_ks#397]
## Describe the Bug
`ensure => absent` requires parameter `certificate` or `certificate_content` set

## Expected Behavior
The `certificate` or `certificate_content` parameter should not be required when removing entries from Keystores

## Steps to Reproduce
1. Create java_ks resource with parameter
`ensure => absent`
but do not set the `certificate` or `certificate_content` parameter

Puppet will fail with:
> Error: Failed to apply catalog: Validation of Java_ks[name_goes_here] failed: You must pass one of 'certificate' or 'certificate_content'

## Environment
 - Version v4.3.0

**Comment by chelnak** [comment]
Hello! Sorry hear that this one slipped through the net. I'm going to do some investigation now and also check out the PR from @tparkercbn .
